#!/usr/bin/env bash
set -euo pipefail
ROOT="$(cd "$(dirname "$0")/../../../.." && pwd)"
cd "$ROOT/web"
test -d node_modules/mermaid || npm ci --no-audit --no-fund
npx --yes esbuild scripts/mermaid-validate-entry.mjs \
  --bundle --platform=node --format=esm --minify \
  --alias:dompurify=./scripts/dompurify-stub.mjs \
  --outfile=../server/internal/mcp/mermaidvalidate/bundle.mjs \
  --banner:js='/* mermaid 11.x syntax validator for set_plan — generated by regen.sh */'
ls -lh ../server/internal/mcp/mermaidvalidate/bundle.mjs
